### ISSUE TITLE
Recipe for opencpop database

### ISSUE THREAD

**Issue by r9y9** [nnsvs/nnsvs#105]
https://wenet.org.cn/opencpop/

It would be great if we can support Mandarin SVS using opencpop database.

**Comment by dtx525942103** [comment]
waiting for you

**Comment by r9y9** [comment]
To be honest, I am also waiting for contribution. I may try making recipes at some point but not sure if I can do it since I don't speak Chinese at all.

**Comment by Archivoice** [comment]
It would be possible to do this as a hed for Chinese exists now, but the main issue would be to convert the labels from textgrid format to HTK label format, and to fix up the labeling because they way the labels are done could cause issues with the timelag and duration models which would possibly affect the acoustic model

**Comment by r9y9** [comment]
I guess converting textgrid files into HTK labels is not that difficult. That said, I plan to seek other input types rather than HTK labels to implement opencpop recipes easily.

**Comment by r9y9** [comment]
For the record, the amount of data:

- 5.21 hours
- 4.35 hours (excluding SP/AP segments)

Noticed that a fair amount of data (approx. 16%) is considered non-voiced sounds.

**Comment by r9y9** [comment]
List of utterances that have long (>5 sec.) silences:
- 2020000775
- 2020000795
- 2048001806
- 2048001826
- 2087003218

Not sure why these long silences are included.

**Comment by r9y9** [comment]
Uploaded samples to https://r9y9.github.io/projects/nnsvs/. Will make a PR for the recipes after #175 gets merged.
