### ISSUE TITLE
Using Enunu english model on NNSVS

### ISSUE THREAD

**Issue by mathigatti** [nnsvs/nnsvs#189]
Hi! I'm trying to use NNSVS with some english Enunu models I found but I'm not getting it to sing english, it just says "oh oh oh oh", am I missing something?

I tweaked a bit the demo colab so it first converts the Enunu model to NNSVS format. [Here](https://colab.research.google.com/drive/1sav1XgtixAslFdbDXsVMF-Zloe5-prVX#scrollTo=gXkF-MUzXt-H) is the colab to replicate my problem and check the audio I'm getting. I'm testing it with the english musicXML file from [sinsy.jp](https://sinsy.jp/)  (My grandfather's clock), I also tried it with phonetic arpabet notation (the two-letter one in lower case).

I tested it with 2 models, I get a similar issue with both.
- [MavaAI_ENGMin.7z](https://drive.google.com/file/d/1_RaezjfgNr1c9PVsK5N78QKZVtG4Zyp9/edit)
- [caleb-beta.zip](https://drive.google.com/file/d/1Fop-6p69iStuViB9qjjIRU6EOM4HylUY/view)

**Comment by r9y9** [comment]
Hi, sorry for the super delay. I looked into the notebook and trained models. It is likely that the models were trained with UST (not musicXML) and thus is not compatible with Sinsy. It is worth trying a UST file as input instead of a musicXML file. I suppose code something like https://github.com/nnsvs/nnsvs/blob/65d3506db6040571d20cbaccb9554a8ec7eff1f3/neutrino_compat/bin/NEUTRINO.py#L72-L85 will work with the English dictionary.

**Comment by mathigatti** [comment]
Hey! Thanks for the answer. Okay, so I got a sample english UST from [here[(https://www.youtube.com/watch?v=aaKkNPmRcj0&ab_channel=carbylover). I should run that NEUTRINO.py but changing the table_path to an english one and then using the output of it to run [NSF.py](https://github.com/nnsvs/nnsvs/blob/65d3506db6040571d20cbaccb9554a8ec7eff1f3/neutrino_compat/bin/NSF.py) ?

**Comment by r9y9** [comment]
Well, I quickly looked into the UST, but the phonemes used by the pretrained models and UST are not compatible. 

It should be okay to use `nnsvs.svs.SPSVS` module. You don't need to run NEUTRINO.py. First you need to prepare UST with appropriate phonemes.
