### ISSUE TITLE
Setup steramlit demo

### ISSUE THREAD

**Issue by r9y9** [nnsvs/nnsvs#83]
So that people can try easily try it out

**Comment by nicolalandro** [comment]
For this issue it is possible to create a demo like I do in [that repo](https://github.com/nicolalandro/streamlit_music_demo) by change the generate wav part with the nnsvs part.

![demo](https://raw.githubusercontent.com/nicolalandro/streamlit_music_demo/main/imgs/demo.png)

https://github.com/nicolalandro/streamlit_music_demo/blob/845c693fa3712f9cb170310c65866a5dfbf513a8/app.py

**Comment by r9y9** [comment]
That would be great!!

**Comment by nicolalandro** [comment]
So I'm waiting the [colab issue](https://github.com/r9y9/nnsvs/issues/78) or any other guide to get in touch with the operations that I will put into generation part.

Thank you!

**Comment by nicolalandro** [comment]
I made the pull request https://github.com/r9y9/nnsvs/pull/87 with basic streamlit app, I'm not shure about to save the wav file because it seams distorted, I'm waiting your check. 

If that work is acceptable It is possible to introduce Docker ? Do you want to see the partiture of loaded file into the demo? 
I waiting your response to add other needed features.

**Comment by r9y9** [comment]
Deployed https://share.streamlit.io/r9y9/nnsvs/streamlit_demo/app.py

**Comment by nicolalandro** [comment]
No problem, I create Merge request https://github.com/r9y9/nnsvs/pull/89 with the musical score visualization. It require python library music21 and system lib lillypond (I think into the streamlit server deploy it is possible to specify inside a package.txt file).
